#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_60_ansi_split_bs_rshift(
        QK_GESC,       KC_1,          KC_2,          KC_3,          KC_4,          KC_5,          KC_6,          KC_7,          KC_8,          KC_9,          KC_0,          KC_MINS,       KC_EQL,        KC_BSLS,       KC_GRV,
        KC_TAB,        KC_Q,          KC_W,          KC_E,          KC_R,          KC_T,          KC_Y,          KC_U,          KC_I,          KC_O,          KC_P,          KC_LBRC,       KC_RBRC,       KC_BSPC,
        KC_LCTL,       LSFT_T(KC_A),  LGUI_T(KC_S),  LT(2,KC_D),   LCTL_T(KC_F),  LALT_T(KC_G),  RALT_T(KC_H),  RCTL_T(KC_J),  LT(2,KC_K),    RGUI_T(KC_L),  RSFT_T(KC_SCLN),KC_QUOT,       KC_ENT,
        KC_LSFT,       KC_Z,          KC_X,          KC_C,          LGUI_T(KC_V),  KC_B,          RGUI_T(KC_N),  KC_M,          KC_COMM,       KC_DOT,        KC_SLSH,       KC_RSFT,       MO(1),
        KC_LCTL,       KC_LGUI,       KC_LALT,       LT(3,KC_SPC),                                               MO(1),         MO(4),         KC_APP,        KC_RCTL
    ),
    [1] = LAYOUT_60_ansi_split_bs_rshift(
        KC_PWR,        KC_F1,         KC_F2,         KC_F3,         KC_F4,         KC_F5,         KC_F6,         KC_F7,         KC_F8,         KC_F9,         KC_F10,        KC_F11,        KC_F12,        KC_INS,        KC_DEL,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_PGUP,       KC_HOME,       KC_UP,         KC_END,        KC_DEL,        KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_PGDN,       KC_LEFT,       KC_DOWN,       KC_RGHT,       KC_PENT,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_LBRC,       KC_RBRC,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,                                                    KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS
    ),
    [2] = LAYOUT_60_ansi_split_bs_rshift(
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_1,          KC_2,          KC_3,          KC_4,          KC_5,          KC_6,          KC_7,          KC_8,          KC_9,          KC_0,          KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_ESC,        KC_TRNS,       TG(2),         KC_BSPC,       KC_TRNS,       KC_TRNS,       KC_TRNS,       TG(2),         KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,                                                    KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS
    ),
    [3] = LAYOUT_60_ansi_split_bs_rshift(
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_PGUP,       KC_HOME,       KC_UP,         KC_END,        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_LSFT,       KC_LGUI,       KC_TRNS,       KC_LCTL,       KC_LALT,       KC_PGDN,       KC_LEFT,       KC_DOWN,       KC_RGHT,       KC_LALT,       KC_RSFT,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_LGUI,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,
        KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS,                                                    KC_TRNS,       KC_TRNS,       KC_TRNS,       KC_TRNS
    ),
    [4] = LAYOUT_60_ansi_split_bs_rshift(
        KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_PSCR,
        KC_NO,         KC_NO,         KC_NO,         QK_BOOT,       KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_VOLU,       KC_NO,         KC_NO,         KC_NO,
        KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_VOLD,       KC_NO,         KC_NO,
        KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_NO,         KC_MPRV,       KC_MNXT,       KC_MPLY,       KC_NO,         KC_NO,
        KC_NO,         KC_NO,         KC_NO,         KC_NO,                                                      KC_NO,         KC_NO,         KC_NO,         KC_NO
    )
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C
