#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_5(
        KC_TAB,     KC_Q,           KC_W,           KC_E,           KC_R,           KC_T,           KC_Y,           KC_U,           KC_I,               KC_O,           KC_P,               KC_BSPC,
        KC_RCTL,    RALT_T(KC_A),   RCTL_T(KC_S),   LT(2,KC_D),     LSFT_T(KC_F),   LALT_T(KC_G),   LALT_T(KC_H),   RSFT_T(KC_J),   LT(2,KC_K),         RCTL_T(KC_L),   RALT_T(KC_QUOT),    KC_QUOT,
        KC_LSFT,    LSFT_T(KC_Z),   LCTL_T(KC_X),   LALT_T(KC_C),   LGUI_T(KC_V),   KC_B,           KC_N,           LGUI_T(KC_M),   LALT_T(KC_COMM),    LCTL_T(KC_DOT), RSFT_T(KC_SLSH),    KC_RSFT,
                    KC_LCTL,        SH_OS,          LT(4,KC_S),     LT(2,KC_BSPC),  KC_RALT,        KC_LGUI,        TT (1),         LT(1,KC_SPC),       RCTL_T(KC_ESC), KC_RCTL
    )
    // [1] = LAYOUT_split_3x6_5(
    //     KC_Q,       KC_BSPC,     KC_DEL, KC_ESC, LCTL(KC_SPC), KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_BSPC, RALT_T(KC_A), RCTL_T(KC_S), LT(2,KC_D), LSFT_T(KC_F), LALT_T(KC_TAB), LALT_T(KC_LEFT), RSFT_T(KC_DOWN), LT(2,KC_UP), RCTL_T(KC_RGHT), RALT_T(KC_SCLN), LSFT_T(KC_Z), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_V), LCTL(KC_B), KC_LBRC, LGUI_T(KC_SPC), LALT_T(KC_RBRC), LCTL_T(KC_DOT), RSFT_T(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // [2] = LAYOUT_split_3x6_5(
    //     KC_Q,       KC_BSPC,     KC_DEL, KC_ESC, QK_USER_1, CW_TOGG, KC_MINS, KC_EQL, KC_COLN, KC_BSPC, RALT_T(KC_1), RCTL_T(KC_2), LT(2,KC_3), LSFT_T(KC_4), LALT_T(KC_5), LALT_T(KC_6), RSFT_T(KC_7), LT(2,KC_8), RCTL_T(KC_9), RALT_T(KC_0), LSFT_T(KC_GRV), LCTL_T(QK_USER_0), LALT_T(KC_COPY), LGUI_T(KC_PSTE), CW_TOGG, KC_BSLS, LGUI_T(KC_0), LALT_T(KC_SLSH), LCTL_T(KC_DOT), RSFT_T(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // [3] = LAYOUT_split_3x6_5(
    //     CG_RSWP,    CG_RNRM,     QK_BOOT, DB_TOGG, KC_NO, KC_NO, KC_NO, KC_NO, KC_VOLU, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MUTE, KC_VOLD, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_MNXT, KC_MPLY, LGUI(KC_L), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // [4] = LAYOUT_split_3x6_5(
    //     OS_LSFT,    KC_BSPC,     KC_E, KC_ESC, QK_USER_2, KC_SLSH, KC_7, KC_8, KC_9, KC_BSPC, RALT_T(KC_A), RCTL_T(KC_DOT), LT(2,KC_D), LSFT_T(KC_F), LALT_T(KC_E), KC_DOT, KC_4, KC_5, KC_6, KC_TAB, LSFT_T(QK_USER_3), LCTL_T(KC_X), LALT_T(KC_C), LGUI_T(KC_G), KC_B, KC_0, KC_1, KC_2, KC_3, KC_ENT, SH_OS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // [5] = LAYOUT_split_3x6_5(
    //     KC_TRNS,    KC_TRNS,     KC_TRNS, KC_WBAK, KC_WFWD, MS_WHLL, MS_WHLD, MS_WHLU, MS_WHLR, KC_NO, MS_BTN4, MS_BTN2, MS_BTN3, MS_BTN1, MS_BTN5, MS_LEFT, MS_DOWN, MS_UP, MS_RGHT, MS_BTN1, KC_LSFT, MS_ACL2, MS_ACL1, MS_ACL0, KC_RCTL, KC_RCTL, KC_LGUI, KC_LALT, KC_LCTL, KC_RSFT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
    // [6] = LAYOUT_split_3x6_5(
    //     KC_Q,       KC_BSPC,     KC_DEL, KC_ESC, QK_USER_1, KC_F11, KC_F12, KC_F13, KC_F14, KC_F15, RALT_T(KC_F1), RCTL_T(KC_F2), LT(2,KC_F3), LSFT_T(KC_F4), LALT_T(KC_F5), LALT_T(KC_F6), RSFT_T(KC_F7), LT(2,KC_F8), RCTL_T(KC_F9), RALT_T(KC_F10), LSFT_T(KC_GRV), LCTL_T(QK_USER_0), LALT_T(KC_COPY), LGUI_T(KC_PSTE), CW_TOGG, KC_BSLS, LGUI_T(KC_0), LALT_T(KC_COMM), LCTL_T(KC_DOT), RSFT_T(KC_ENT), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

